package actual_working;

import java.io.Serializable;

import OwnList.RowItem;

import com.example.cocktailmixxer.R;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Saft.java
//  @ Date : 31.10.2013
//  @ Author : 
//
//




public class Saft extends RowItem implements Serializable,Cloneable{
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	public Saft(String title, String description) {
		super(imageId, title, "-");
		// TODO Auto-generated constructor stub
	}
	
	private int S_ID;
	private int procent=0;
	private int ml =0;
	public int getMl() {
		return procent*500/100;
	}

	public void setMl(int ml) {
		this.ml = ml;
	}

	private String Name;
	private String decs;
	public int getProcent() {
		return procent;
	}
	public Object clone() throws CloneNotSupportedException
    {
        /* Hier wird die Methode clone der Superklasse(in diesem Falle Object) aufgerufen. */
        return super.clone();
    }
	public void setProcent(int procent) {
		this.procent = procent;
	}

	static int imageId=R.drawable.saeft_icon;
	private double AlkGehalt;
	private int Behaelter;
	public String Kategorie;
	public void setName() {
	
	}
	
	public void setAlkGehalt() {
	
	}
	
	public void setBehaelter() {
	
	}
	
	public void setKategorie() {
	
	}
	
	public void getAlkMl() {
	
	}
	
	public String toString() {
		return "";
	}
	public void setdescNormal(){
		super.setDesc("---");
	}
	public void setDescList(){
		super.setDesc("Getränkanteil im Cocktail: \n"+Math.round(procent)+" %"+"\n"+procent*Math.round((500/100))+" ml");
		
	}
}
