package projekt.helpclasses;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import projekt.OwnList.RowItem;

import com.example.cocktailmixxer.R;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Cocktail.java
//  @ Date : 31.10.2013
//  @ Author : 
//
//




public class Cocktail extends RowItem implements Serializable{
	static String Name;
	int C_ID;
	static String desc;

	final public int cocktailsize = 500;
	int mlLeft=cocktailsize;
	int mlFull=0;
	List<? super Saft> SaftList_cocktail;
	Saft activeSaft;
	//Gibt bytes zurück die per bluetooth gesendet werden
	public byte[] getBluetoothSignal() {
		String returnStr = "";
		for (int i = 0; i < SaftList_cocktail.size(); i++) {
			returnStr+="  "+((Saft) SaftList_cocktail.get(i)).getMl();
		}
		return returnStr.getBytes();
	}
	public Saft getActiveSaft() {
		return activeSaft;
	}

	public void setActiveSaft(Saft activeSaft) {
		this.activeSaft = activeSaft;
	}

	static int imageId = R.drawable.icon_cocktail;

	
	public Cocktail(int imageId, String title, String desc) {
		super(imageId, title, desc);
		Name = title;
		this.desc = desc;
		SaftList_cocktail = (List<Saft>) new ArrayList<Saft>();

	}

	public void setSaftList_cocktail(List<? super Saft> saftList_cocktail) {
		SaftList_cocktail = saftList_cocktail;
	}

	public void setName(String name) {
		super.setTitle(name);
	}

	public void setDesc(String info) {
		super.setDesc(info);
	}



	public int getMlLeft() {
		return mlLeft;
	}

	public void setMlLeft(int mlLeft) {
		this.mlLeft = mlLeft;
	}

	
	public void getC_ID() {

	}

	public List<RowItem> get_SaftList_cocktail() {
		return (List<RowItem>) SaftList_cocktail;
	}

	public void addSaft(Saft saft) {
		for (int i = 0; i < SaftList_cocktail.size(); i++) {
			if(((Saft)SaftList_cocktail.get(i)).getTitle()==saft.getTitle()){
				
				SaftList_cocktail.remove(i);
				
			}
		}
		SaftList_cocktail.add(saft);
	}

	public String toString() {
		return "";
	}
	@Override
	public boolean equals(Object o) {
		return super.equals(o);
	}

}
