//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : User.java
//  @ Date : 28.10.2013
//  @ Author : 
//
//




public class User {
	public Integer ID;
}
